### ISSUE TITLE
Consider publishing on OpenVSX

### ISSUE THREAD

**Issue by RivenSkaye** [tiffany352/tiffcolors#3]
With MS limiting the use of the VSC extension marketplace to only their product (excluding alternatives like VS Codium), OpenVSX popped up for people using non-MS builds.
The OpenVSX repo has a rather large template, but they do list severl of the alternatives already using it as default ([VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs)
[Publishing docs](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) are available.

If you'd prefer not to, feel free to close the issue. Though I'd like to ask for permission to use this theme with Codium on my private machine in that case

**Comment by tiffany352** [comment]
Thanks for the heads up, I'll try publishing it there.

**Comment by tiffany352** [comment]
Published: https://open-vsx.org/extension/tiffnix/tiffcolors

I installed it in VSCodium and it worked. Trying to claim the `tiffnix` namespace as well. (https://github.com/EclipseFdn/open-vsx.org/issues/1394)
